/*
 * File: FreeRTOSPlatformContract.h
 *
 * Purpose:
 *   The contract between the shared FreeRTOSConfig.h and the platform. A
 *   platform is one osal_freertos_platform() call in its BSP's
 *   CMakeLists.txt, which checks the required settings at configure time
 *   and generates FreeRTOSConfigPlatform.h from them - the settings are
 *   listed in generic-freertos/osal_freertos_platform.cmake. The shared
 *   config only ever consumes the OSAL_FREERTOS_PLATFORM_* macros that
 *   header defines; this file supplies the defaults for the optional ones.
 */

#ifndef FREERTOS_PLATFORM_CONTRACT_H
#define FREERTOS_PLATFORM_CONTRACT_H

#ifndef OSAL_FREERTOS_PLATFORM_GENERATED
#error "FreeRTOSConfigPlatform.h must be generated by osal_freertos_platform()"
#endif

#ifndef OSAL_FREERTOS_PLATFORM_OPTIMISED_TASK_SELECTION
#define OSAL_FREERTOS_PLATFORM_OPTIMISED_TASK_SELECTION 0
#endif

#ifndef OSAL_FREERTOS_PLATFORM_WEAK
#define OSAL_FREERTOS_PLATFORM_WEAK __attribute__((weak))
#endif

#endif /* FREERTOS_PLATFORM_CONTRACT_H */
